CouponVerifier/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("verification/", include('verification.urls', namespace='verification'))
]

verification/urls.py
from django.urls import path
from . import views


app_name = "verification"

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("verify/", views.verify, name="verify"),
]

verification/models.py
from django.db import models
from CouponVerifier.settings import AUTH_USER_MODEL


status_choice = [("未使用", "未使用"), ("已使用", "已使用"), ("作废", "作废"), ("无效", "无效")]


class Coupon(models.Model):
    id = models.AutoField(primary_key=True)
    customer_id = models.CharField(max_length=300, verbose_name="客户id")
    coupon_type = models.CharField(max_length=30, verbose_name="券码类型")
    coupon = models.CharField(max_length=300, unique=True, verbose_name="券码")
    signature = models.CharField(max_length=1000, verbose_name="校验码")
    version = models.CharField(max_length=30, verbose_name="密钥版本")
    created_datetime = models.DateTimeField(verbose_name="创建时间")
    valid_from_datetime = models.DateTimeField(verbose_name="生效时间")
    expiry_datetime = models.DateTimeField(verbose_name="过期时间")
    status = models.CharField(max_length=30, choices=status_choice, verbose_name="状态")
    uploaded_user = models.ForeignKey(AUTH_USER_MODEL, related_name="coupon_uploaded_user", on_delete=models.DO_NOTHING, verbose_name="上传用户")
    uploaded_datetime = models.DateTimeField(auto_now_add=True, verbose_name="上传时间")
    updated_user = models.ForeignKey(AUTH_USER_MODEL, related_name="coupon_updated_user", on_delete=models.DO_NOTHING, verbose_name="最后更新用户")
    updated_datetime = models.DateTimeField(auto_now=True, verbose_name="最后更新时间")

    class Meta:
        verbose_name = "券码"
        verbose_name_plural = "券码"
        indexes = [
            models.Index(fields=['coupon'])
        ]

    def __str__(self):
        return str(self.id)


class CouponSummary(Coupon):

    class Meta:
        proxy = True
        verbose_name = "券码统计"
        verbose_name_plural = "券码统计"

CouponVerifier/views.py
from django.shortcuts import redirect, reverse


def check_authority(func):
    def wrapper(*args, **kwargs):
        if not args[0].user.is_authenticated:
            # if "X-Requested_With" in args[0].headers:
            #     return JsonResponse('请先登录', safe=False, json_dumps_params={'ensure_ascii': False})
            if args[0].META['QUERY_STRING']:
                return redirect(reverse('verification:login') + '?next=%s?%s' % (args[0].path, args[0].META['QUERY_STRING']))
            return redirect(reverse('verification:login') + '?next=%s' % args[0].path)
        return func(*args, **kwargs)
    return wrapper

verification/views.py
import datetime
from django.shortcuts import render, redirect, reverse
from verification.models import Coupon
from pytz import timezone
from CouponVerifier.settings import TIME_ZONE, AUTH_USER_MODEL
from CouponVerifier.rsa_handler import RsaHandler
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_admin
from django.contrib.auth import logout as logout_admin
from django.contrib.auth.hashers import check_password
from CouponVerifier.views import check_authority
from urllib import parse


time_zone = timezone(TIME_ZONE)


@check_authority
def home(request):
    return render(request, 'verification.html')


# 解析url中的参数
def parse_url_param(url):
    url_content = parse.urlparse(url)
    query_dict = parse.parse_qs(url_content.query)
    return query_dict


@check_authority
def verify(request):
    if request.method == "POST":
        coupon_code = request.POST.get("coupon", "")
        if not coupon_code:
            messages.error(request, "请输入券码")
            return redirect(reverse('verification:home'))
        try:
            coupon = Coupon.objects.get(coupon=coupon_code)
        except:
            messages.error(request, "未找到该券码")
            return redirect(reverse('verification:home'))
        rsa_handler = RsaHandler(coupon.version)
        if not rsa_handler.is_key_exist():
            messages.error(request, "没有该版本的券码校验文件")
            return redirect(reverse('verification:home'))
        rsa_handler.load_keys()
        result = rsa_handler.verify_text(coupon.coupon, coupon.signature)
        if not result:
            coupon.status = "无效"
            coupon.updated_user = request.user
            coupon.save()
            messages.error(request, "校验失败，此券码为无效券码")
            return redirect(reverse('verification:home'))
        dt = time_zone.localize(datetime.datetime.now())
        if coupon.valid_from_datetime <= dt <= coupon.expiry_datetime:
            if coupon.status == "未使用":
                coupon.status = "已使用"
                coupon.updated_user = request.user
                coupon.save()
                messages.success(request, '核销成功！准入区域：%s' % coupon.coupon_type)
                return redirect(reverse('verification:home'))
            else:
                messages.error(request, "核销失败！券码不可用，状态为：%s" % coupon.status)
                return redirect(reverse('verification:home'))
        else:
            if dt < coupon.valid_from_datetime:
                messages.error(request, "核销失败！该券码未生效")
                return redirect(reverse('verification:home'))
            elif dt > coupon.expiry_datetime:
                messages.error(request, "核销失败！该券码已过期")
                return redirect(reverse('verification:home'))
    else:
        return render(request, "verification.html", {"msg_cn": "请求错误"})


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            login_admin(request, user)
            next_url = request.META.get("HTTP_REFERER", '')
            next_url_params = parse_url_param(next_url)
            if next_url_params:
                try:
                    next_url = next_url_params['next'][0]
                    return redirect(next_url)
                except:
                    return redirect(reverse('verification:home'))
            else:
                return redirect(reverse('verification:home'))
        else:
            try:
                user = AUTH_USER_MODEL.objects.get(username=username)
                if check_password(password, user.password):
                    if user.is_active:
                        messages.error(request, "登录失败！请联系管理员")
                        return redirect(reverse('verification:login'))
                    else:
                        messages.error(request, "登录失败！该账号未启用")
                        return redirect(reverse('verification:login'))
                else:
                    messages.error(request, "登录失败！用户名或密码错误")
                    return redirect(reverse('verification:login'))
            except:
                messages.error(request, "登录失败！用户名或密码错误")
                return redirect(reverse('verification:login'))
    else:
        if request.user.is_authenticated:
            return redirect(reverse('verification:home'))
        else:
            next_url = request.GET.get('next', '')
            return render(request, 'login.html', {'next': next_url})


def logout(request):
    logout_admin(request)
    messages.success(request, "登出成功！")
    return redirect(reverse('verification:login'))

templates/done.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        {% include "head.html" %}
        <title>结果</title>
    </head>
    <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
            <!-- Page Content-->
            <section class="py-5">
                <div class="container px-5 my-5">
                    <div class="row gx-5 justify-content-center">
                        <div class="col-lg-6">
                            <div class="text-center mb-5">
                                <h1 class="fw-bolder"><img style="width: 9%" src="{% static 'assets/success.png'%}"/>结果 Result</h1>
                                <p class="lead fw-normal text-muted mb-0">{{ msg_cn }}</p>
                                <p class="lead fw-normal text-muted mb-0">{{ msg_en }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>
        <!-- Bootstrap core JavaScript -->
        {% include "script.html" %}
    </body>
</html>

templates/error.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        {% include "head.html" %}
        <title>结果</title>
    </head>
    <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
            <!-- Page Content-->
            <section class="py-5">
                <div class="container px-5 my-5">
                    <div class="row gx-5 justify-content-center">
                        <div class="col-lg-6">
                            <div class="text-center mb-5">
                                <h1 class="fw-bolder"><img style="width: 7%" src="{% static 'assets/error.png'%}"/>结果 Result</h1>
                                <p class="lead fw-normal text-muted mb-0">{{ msg_cn }}</p>
                                <p class="lead fw-normal text-muted mb-0">{{ msg_en }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>
        <!-- Bootstrap core JavaScript -->
        {% include "script.html" %}
    </body>
</html>

templates/error_400.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    {% include "head.html" %}
    <title>400</title>

</head>

<body>

<!-- Navigation -->
{% include "navigation.html" %}

<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">400
        <small>请求错误</small>
    </h1>

    <ol class="breadcrumb">
        {% include "route.html" %}
        <li class="breadcrumb-item active">400</li>
    </ol>

    <div class="jumbotron">
        <h1 class="display-5">请求错误！</h1>
        <br>
        {% include "error_redirect.html" %}
    </div>
    <!-- /.jumbotron -->

</div>
<!-- /.container -->

<!-- Footer -->
{% include "footer.html" %}

<!-- Bootstrap core JavaScript -->
{% include "script.html" %}

</body>

</html>

templates/error_403.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    {% include "head.html" %}
    <title>403</title>

</head>

<body>

<!-- Navigation -->
{% include "navigation.html" %}

<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">403
        <small>请求被拒绝</small>
    </h1>

    <ol class="breadcrumb">
        {% include "route.html" %}
        <li class="breadcrumb-item active">403</li>
    </ol>

    <div class="jumbotron">
        <h1 class="display-5">请求被服务器拒绝了！</h1>
        <br>
        {% include "error_redirect.html" %}
    </div>
    <!-- /.jumbotron -->

</div>
<!-- /.container -->

<!-- Footer -->
{% include "footer.html" %}

<!-- Bootstrap core JavaScript -->
{% include "script.html" %}

</body>

</html>

templates/error_404.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    {% include "head.html" %}
    <title>404</title>

</head>

<body>

<!-- Navigation -->
{% include "navigation.html" %}

<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">404
        <small>页面未找到</small>
    </h1>

    <ol class="breadcrumb">
        {% include "route.html" %}
        <li class="breadcrumb-item active">404</li>
    </ol>

    <div class="jumbotron">
        <h1 class="display-5">迷路了吗？</h1>
        <br>
        {% include "error_redirect.html" %}
    </div>
    <!-- /.jumbotron -->

</div>
<!-- /.container -->

<!-- Footer -->
{% include "footer.html" %}

<!-- Bootstrap core JavaScript -->
{% include "script.html" %}

</body>

</html>

templates/error_500.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    {% include "head.html" %}
    <title>500</title>

</head>

<body>

<!-- Navigation -->
{% include "navigation.html" %}

<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">500
        <small>服务器出现问题</small>
    </h1>

    <ol class="breadcrumb">
        {% include "route.html" %}
        <li class="breadcrumb-item active">500</li>
    </ol>

    <div class="jumbotron">
        <h1 class="display-5">服务器出问题了！</h1>
        <br>
        {% include "error_redirect.html" %}
    </div>
    <!-- /.jumbotron -->

</div>
<!-- /.container -->

<!-- Footer -->
{% include "footer.html" %}

<!-- Bootstrap core JavaScript -->
{% include "script.html" %}

</body>

</html>

templates/error_redirect.html
{% load static %}
<p>点击下列链接跳转:</p>
<ul>
    <li>
        <a href="/">首页</a>
    </li>
    <li>
        功能模块
        <ul>
            <li>
                <a href="/performance">绩效管理</a>
            </li>
        </ul>
    </li>
    <li>
        其他
        <ul>
            <li>
                <a href="/about">关于</a>
            </li>
            <li>
                <a href="/contect">联系我们</a>
            </li>
        </ul>
    </li>
</ul>

templates/footer.html
{% load static %}
<footer class="bg-dark py-4 mt-auto" style="background-color: rgba(189,15,16,0.9);">
    <div class="container px-5">
        <div class="row align-items-center justify-content-between flex-column flex-sm-row">
            <div class="col-auto"><div class="small m-0 text-white"></div></div>
            <div class="col-auto">
                <a class="link-light small" href="#!"></a>
                <span class="text-white mx-1">&middot;</span>
                <a class="link-light small" href="#!"></a>
                <span class="text-white mx-1">&middot;</span>
                <a class="link-light small" href="#!"></a>
                <span class="text-white mx-1">&middot;</span>
            </div>
        </div>
    </div>
</footer>

templates/head.html
{% load static %}
<!-- href="{% static "img/favicon.png" %}" -->
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<meta name="description" content />
<meta name="author" content />
<!-- Favicon-->
<link rel="icon" type="image/x-icon" href="{% static 'assets/logo.ico' %}" />
<!-- Bootstrap icons-->
<!--<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />-->
<!-- Core theme CSS (includes Bootstrap)-->
<link href="{% static 'css/styles.css' %}" rel="stylesheet" />

templates/header.html
{% load static %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-5">
        <div class="row gx-5 align-items-center justify-content-center">
            <div class="col-lg-8 col-xl-7 col-xxl-6">
                <div class="my-5 text-center text-xl-start">
                    <h1 class="display-5 fw-bolder text-white mb-2">A Bootstrap 5 template for modern businesses</h1>
                    <p class="lead fw-normal text-white-50 mb-4">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit!</p>
                    <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start">
                        <a class="btn btn-primary btn-lg px-4 me-sm-3" href="#features">Get Started</a>
                        <a class="btn btn-outline-light btn-lg px-4" href="#!">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center"><img class="img-fluid rounded-3 my-5" src="https://dummyimage.com/600x400/343a40/6c757d" alt="..." /></div>
        </div>
    </div>
</header>

templates/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        {% include "head.html" %}
        <title>行程登记主页</title>
    </head>
    <body class="d-flex flex-column">
        <main class="flex-shrink-0">
            <!-- Navigation-->
            {% include "navigation.html" %}
            <div class="container px-5">
                <div class="row justify-content-center">
                    <div class="col-lg-8 col-xxl-6">
                        <div class="text-center my-5">
                            <h1 class="fw-bolder mb-3">行程登记</h1>
                            <p class="lead fw-normal text-muted mb-4">数据仅用于行程登记与模板生成<br/>请于每日工作结束后<strong>清除</strong>当天数据<br/>请<strong>勿</strong>发布此页面</p>
                            <a class="btn btn-primary btn-lg" href="{% url 'export_pax' %}">开始生成</a>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Page Content-->
<!--            <section class="py-5">-->
<!--                <div class="container px-5">-->
<!--                    <h1 class="fw-bolder fs-5 mb-4"></h1>-->
<!--                    <div class="card border-0 shadow rounded-3 overflow-hidden">-->
<!--                        <div class="card-body p-0">-->
<!--                            <div class="row gx-0">-->
<!--                                <div class="col-lg-6 col-xl-5 py-lg-5">-->
<!--                                    <div class="p-4 p-md-5">-->
<!--                                        <div class="badge bg-primary bg-gradient rounded-pill mb-2">News</div>-->
<!--                                        <div class="h2 fw-bolder">行程登记</div>-->
<!--                                        <p>添加旅客预报信息上传、比对功能</p>-->
<!--                                        <a class="stretched-link text-decoration-none" href="/admin">-->
<!--                                            进入后台-->
<!--                                            <i class="bi bi-arrow-right"></i>-->
<!--                                        </a>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--&lt;!&ndash;                                <div class="col-lg-6 col-xl-7"><div class="bg-featured-blog" style="background-image: url('https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fnimg.ws.126.net%2F%3Furl%3Dhttp%253A%252F%252Fdingyue.ws.126.net%252F2021%252F0914%252F2ec4d508j00qzduvz000kd200fc007bg00fc007b.jpg%26thumbnail%3D660x2147483647%26quality%3D80%26type%3Djpg&refer=http%3A%2F%2Fnimg.ws.126.net&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1643251457&t=34227c56103343026c721ef8bc072f23')"></div></div>&ndash;&gt;-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </section>-->

        </main>
        <!-- Footer-->
        {% include "footer.html" %}
        {% include "script.html" %}
    </body>
</html>

templates/message.html
{% load static %}
<div><i style="color:red; font-size:16px;">{{ msg }}</i></div>

templates/navigation.html
{% load static %}
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="{% url 'home' %}">主页</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link" href="{% url 'collect_pax' %}" role="button">行程登记</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="{% url 'export_pax' %}" role="button">模板生成</a>
                </li>
                {% if user.is_authenticated == True %}
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="/admin" role="button">后台管理</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="{% url 'logout' %}" role="button">登出</a>
                    </li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">登录</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/route.html
{% load static %}
<li class="breadcrumb-item">
    <a href="/">首页</a>
</li>

verification/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% include "head.html" %}
    <title>券码兑换</title>
</head>

<body class="d-flex flex-column">
    <main class="flex-shrink-0">

        <!-- Page content-->
        <section class="py-5">
            <div class="container px-5">
                <!-- Contact form-->
                <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
                    <div class="text-center mb-5">
                        <h1 class="fw-bolder">登录</h1>
                        <p class="lead fw-normal text-muted mb-0"></p>
                    </div>
                    <div class="row gx-5 justify-content-center">
                        <div class="col-lg-8 col-xl-6">
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                            <form data-sb-form-api-token="API_TOKEN" action="{% url 'verification:login' %}" method="post">
                                {% csrf_token %}
                                <!-- Name input-->
                                <div class="form-floating mb-3">
                                    <input class="form-control" id="username" name="username" type="text" placeholder="请输入用户名" required/>
                                    <label for="username" style="font-size: 14px">用户名：</label>
                                    <div class="invalid-feedback" id="coupon-invalid-feedback"></div>
                                </div>
                                <div class="form-floating mb-3">
                                    <input class="form-control" id="password" name="password" type="password" placeholder="请输入密码" required/>
                                    <label for="password" style="font-size: 14px">密码：</label>
                                    <div class="invalid-feedback" id="coupon-invalid-feedback"></div>
                                </div>
                                <!-- Submit Button-->
                                <div id="liveAlertPlaceholder"></div>
                                <div align="center" style="color: red">{{ msg_cn }}</div>
                                <div class="d-grid"><button class="btn btn-primary btn-lg" id="submitButton" type="submit">登录</button></div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </section>
    </main>
<!-- Bootstrap core JavaScript -->
{% include "script.html" %}
{% if messages %}
    <script>
        var alertPlaceholder = document.getElementById('liveAlertPlaceholder')
        function alertMessage(message, type) {
            if (type == "error"){
                type = 'danger'
            }
            var wrapper = document.createElement('div')
            wrapper.innerHTML = '<div class="alert alert-' + type + ' alert-dismissible" role="alert">' + message + '<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>'
            alertPlaceholder.append(wrapper)
        }

        {% for msg in messages %}
            alertMessage('{{ msg.message }}', '{{ msg.tags }}')
            window.setTimeout(function(){
                $('.alert').empty().removeClass();
            }, 3000)
        {% endfor %}
    </script>
{% endif %}
</body>
</html>

verification/templates/verification.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% include "head.html" %}
    <title>券码兑换</title>
</head>

<body class="d-flex flex-column">
    <main class="flex-shrink-0">

        <!-- Page content-->
        <section class="py-5">
            <div class="container px-5">
                <!-- Contact form-->
                <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
                    <div class="text-center mb-5">
                        <h1 class="fw-bolder"></h1>
                        <p class="lead fw-normal text-muted mb-0">请输入券码：</p>
                    </div>
                    <div class="row gx-5 justify-content-center">
                        <div class="col-lg-8 col-xl-6">
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                            <form data-sb-form-api-token="API_TOKEN" action="{% url 'verification:verify' %}" method="post">
                                {% csrf_token %}
                                <!-- Name input-->
                                <div class="form-floating mb-3">
                                    <input class="form-control" id="coupon" name="coupon" type="text" placeholder="请输入券码" value="{{ coupon }}" required/>
                                    <label for="coupon" style="font-size: 14px">券码：</label>
                                    <div class="invalid-feedback" id="coupon-invalid-feedback"></div>
                                </div>
                                <!-- Submit Button-->
                                <div id="liveAlertPlaceholder"></div>
                                <div align="center" style="color: red">{{ msg_cn }}</div>
                                <div class="d-grid"><button class="btn btn-primary btn-lg" id="submitButton" type="submit">核销</button></div>
                            </form>
                            <div align="center"><br/><p style="font-size: 12px">当前用户：{{ request.user.username }}, <a href="{% url 'verification:logout' %}">登出</a></p></div>
                        </div>
                    </div>
                </div>

            </div>
        </section>
    </main>
<!-- Bootstrap core JavaScript -->
{% include "script.html" %}
{% if messages %}
    <script>
        var alertPlaceholder = document.getElementById('liveAlertPlaceholder')
        function alertMessage(message, type) {
            if (type == "error"){
                type = 'danger'
            }
            var wrapper = document.createElement('div')
            if (type == "success") {
                wrapper.innerHTML = '<div class="alert alert-' + type + ' alert-dismissible" role="alert" style="font-size: 30px; text-align: center">' + message + '<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>'
            } else {
                wrapper.innerHTML = '<div class="alert alert-' + type + ' alert-dismissible" role="alert" style="font-size: 24px; text-align: center">' + message + '<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>'
            }
            alertPlaceholder.append(wrapper)
        }

        {% for msg in messages %}
            alertMessage('{{ msg.message }}', '{{ msg.tags }}')
            // window.setTimeout(function(){
            //     $('.alert').empty().removeClass();
            // }, 3000)
        {% endfor %}
    </script>
{% endif %}
</body>
</html>